# tf frame with respect to which the spatial relations are computed
string frame_id

# entity names
string entity1
string entity2

# which type of relation (is a string and can use the constants defined below)
string relation_type

# These spatial relations belong to SpatialCalculus.PROJECTIVE spatial calculus
string Top=Top
string Bottom=Bottom
string Right=Right
string Left=Left
string TopRight=TopRight
string TopLeft=TopLeft
string BottomLeft=BottomLeft
string BottomRight=BottomRight
string Ontopof=Ontopof
string Under=Under
string TopOverlapsLeft=TopOverlapsLeft
string TopOverlapsLeftOverlaps=TopOverlapsLeftOverlaps
string TopLeftOverlaps=TopLeftOverlaps
string TopOverlapsRight=TopOverlapsRight
string TopRightOverlaps=TopRightOverlaps
string TopOverlapsRightOverlaps=TopOverlapsRightOverlaps
string BottomOverlapsLeft=BottomOverlapsLeft
string BottomOverlapsLeftOverlaps=BottomOverlapsLeftOverlaps
string BottomLeftOverlaps=BottomLeftOverlaps
string BottomOverlapsRight=BottomOverlapsRight
string BottomOverlapsRightOverlaps=BottomOverlapsRightOverlaps
string BottomRightOverlaps=BottomRightOverlaps 

